steps:
  # Build image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mlops-retail-quant/retail-prediction-api:$SHORT_SHA', '.']

  # Push image to container registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mlops-retail-quant/retail-prediction-api:$SHORT_SHA']

  # Deploy to cloudrun
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'retail-prediction-api'
      - '--image'
      - 'gcr.io/mlops-retail-quant/retail-prediction-api:$SHORT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'me-central1'
      - '--allow-unauthenticated'
      
  # Deploy to Model Registry
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud ai models upload \
          --display-name="Kmeans_Model" \
          --artifact-uri="gs://kmeans_model_bucket/" \
          --region="europe-central2" \
          --container-image-uri="us-docker.pkg.dev/vertex-ai/prediction/sklearn-cpu.0-24:latest"

options:
  logging: CLOUD_LOGGING_ONLY
